export const authorization =
  "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhNzJlMmU3OGQzMmFhN2ZlOTQ2ZDFkMzcwMzAzNzQwZCIsIm5iZiI6MTczNTExNDczNi45MzYsInN1YiI6IjY3NmJiZmYwNzg5YzcxMjViNWE5ZDg1NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.PntTLU3Rgnz3n16AkaPT6eXdCgFmzMGayMtW0o_kaIs";
